sudo: required
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
services:
  - docker
before_install:
  - docker pull rabbitmq:3-management
  - sudo iptables -N DOCKER || true
  - "docker run -d -h rabbit1 -p 5673:5672 -p 15673:15672 -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest --name rabbit1 rabbitmq:3-management"
  - docker ps -a
env:
  - RABBITMQ_HOST=127.0.0.1 RABBITMQ_AMQP_PORT=5673 RABBITMQ_ADMIN_PORT=15673
install:
  - pip install flake8 nose>=1.3.0 coverage coveralls
  - pip install -e .[all]
script:
  - flake8 .
  - python setup.py nosetests
  - coverage report
  - python setup.py build_sphinx
after_success:
  coveralls
