sudo: required
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
services:
  - docker
before_install:
  - docker pull rabbitmq:3-management
  - sudo iptables -N DOCKER || true
  - "docker run -d -h rabbit1 -p 5673:5672 -p 15673:15672 -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest --name rabbit1 rabbitmq:3-management"
  - docker ps -a
install:
  - pip install flake8 nose>=1.3.0 coverage coveralls
  - pip install -e .[all]
script:
  - flake8 .
  # try to wait on rabbit1 to be up
  - for ii in $(seq 1 120); do docker logs rabbit1 | grep 'Server startup complete'; RC=$?; if [ $RC -eq 0 ]; then echo "rabbit is up ii-$ii"; break; else echo "waiting ii-$ii"; fi; sleep 1; done
  - for ii in $(seq 1 120); do curl http://guest:guest@127.0.0.1:15673/api/connections/ | grep '\[\]'; RC=$?; if [ $RC -eq 0 ]; then echo "rabbit-mgmt returned empty connection list ii-$ii"; break; else echo "waiting rabbit-mgmt empty connection list ii-$ii"; fi; sleep 1; done
  - curl http://guest:guest@127.0.0.1:15673/api/connections/
  - python setup.py nosetests
  - coverage report
  - python setup.py build_sphinx
after_success:
  coveralls
